### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by foxcroftjn** [kagisearch/fastfeedparser#10]
Three of the tests are failing (kagi.xml, osm.xml, and stackoverflow.xml). This appears to have started in 5a972e6410d44a3857ed6ef394213bc4ca29f431.

**Comment by foxcroftjn** [comment]
More specifically, this is leading to feed titles not being parsed.

**Comment by vprelovac** [comment]
There was a major refactor, everything should be fine now.
