### ISSUE TITLE
Exception when parsing empty feeds

### ISSUE THREAD

**Issue by foxcroftjn** [kagisearch/fastfeedparser#7]
When parsing a feed with no items, fastfeedparser throws an exception. It would be more useful to get back a feed object that still has keys for the feed title (and other feed metadata) where the `entries` key is set to an empty list. Empty RSS feeds are common for YouTube channels with no recent videos (which is where I am running into this behavior).

**Comment by Zaczero** [comment]
I have prepared a PR if maintainers decide to alter that behavior. I personally agree with this change. It should be up to the library users to decide what to do with empty feeds.
